Repository openshift-psap/topsail, pull requests merged in 2024-02, with the labels that each got.

#208 [notebooks] updates XPaths for RHOAI 2.7
  projects/notebooks/roles/notebooks_ods_ci_scale_test/files/ods-ci/notebook_dsg_test.robot
Labels: ok-to-test

#211 [kserve] prepare longevity testing
  projects/kserve/testing/config.yaml
  projects/kserve/testing/prepare_scale.py
  projects/kserve/testing/test_e2e.py
  projects/kserve/testing/test_scale.py
Labels: approved

#215 [kserve] KPIs for llm-load-test
  projects/kserve/visualizations/kserve-llm/models/kpi.py
  projects/kserve/visualizations/kserve-llm/models/lts.py
  projects/kserve/visualizations/kserve-llm/plotting/lts.py
  projects/kserve/visualizations/kserve-llm/plotting/lts_documentation.py
  projects/kserve/visualizations/kserve-llm/store/lts.py
  projects/kserve/visualizations/kserve-llm/store/lts_parser.py
Labels: approved, lgtm
