Repository openshift-psap/topsail, pull requests merged in 2025-02, with the labels that each got.

#670 Rhoai 2.17 rc
  projects/fine_tuning/testing/config.yaml
  projects/fine_tuning/testing/prepare_finetuning.py
  projects/rhods/toolbox/rhods_undeploy_ods/tasks/main.yml
Labels: do-not-merge/work-in-progress, ok-to-test

#675 [fine_tuning] Update max_seq_length for QLoRA validation
  projects/fine_tuning/testing/config.yaml
Labels: ok-to-test, approved, lgtm

#679 Drop hyper_parameters.skip_if from settings
  projects/fine_tuning/visualizations/fine_tuning/store/__init__.py
Labels: approved, lgtm

#667 [pipelines] update to RHOAI 2.17.0rc1
  projects/pipelines/testing/config.yaml
Labels: approved, lgtm

#676 [TOPSAIL] Small convenience improvements
  .gitignore
  launcher/topsail_enter
  projects/core/library/ansible_toolbox.py
  projects/core/library/config.py
  projects/core/library/run.py
  projects/matrix_benchmarking/library/visualize.py
  projects/matrix_benchmarking/visualizations/helpers/store/__init__.py
  variable_overrides.yaml.sample
Labels: approved, lgtm

#681 Enable Topsail container in MacOS
  build/Dockerfile
Labels: approved, lgtm

#686 Run fms-hf-tuning perf tests for RHOAI 2.18.0 RC1
  projects/fine_tuning/testing/config.yaml
Labels: ok-to-test, approved, lgtm
